CREATE TABLE [dbo].[CardiologicalECG] (
    [CardiologicalECGId]      INT            IDENTITY (1, 1) NOT NULL,
    [ResidentId]              INT            NULL,
    [CardiologicalECGDate]    DATE           NULL,
    [HR]                      INT            NULL,
    [RhythmTypeID]            INT            NULL,
    [AxisDegree]              NVARCHAR (50)  NULL,
    [PQ]                      INT            NULL,
    [QT]                      INT            NULL,
    [LVHId]                   INT            NULL,
    [RVHId]                   INT            NULL,
    [ZoneIshemiaId]           INT            NULL,
    [ZoneInfarctionId]        INT            NULL,
    [LaunId]                  INT            NULL,
    [PAC]                     BIT            NULL,
    [ConductionDisturbanceId] INT            NULL,
    [BBBId]                   INT            NULL,
    [Comment]                 NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CardiologicalECG] PRIMARY KEY CLUSTERED ([CardiologicalECGId] ASC),
    CONSTRAINT [FK_CardiologicalECG_BBB] FOREIGN KEY ([BBBId]) REFERENCES [dbo].[BBB] ([BBBId]),
    CONSTRAINT [FK_CardiologicalECG_ConductionDisturbance] FOREIGN KEY ([ConductionDisturbanceId]) REFERENCES [dbo].[ConductionDisturbance] ([ConductionDisturbanceId]),
    CONSTRAINT [FK_CardiologicalECG_ECGZone] FOREIGN KEY ([ZoneIshemiaId]) REFERENCES [dbo].[ECGZone] ([ECGZoneId]),
    CONSTRAINT [FK_CardiologicalECG_ECGZone1] FOREIGN KEY ([ZoneInfarctionId]) REFERENCES [dbo].[ECGZone] ([ECGZoneId]),
    CONSTRAINT [FK_CardiologicalECG_Laun] FOREIGN KEY ([LaunId]) REFERENCES [dbo].[Laun] ([LaunId]),
    CONSTRAINT [FK_CardiologicalECG_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE,
    CONSTRAINT [FK_CardiologicalECG_RhythmType] FOREIGN KEY ([RhythmTypeID]) REFERENCES [dbo].[RhythmType] ([RhythmTypeId]),
    CONSTRAINT [FK_CardiologicalECG_VH] FOREIGN KEY ([LVHId]) REFERENCES [dbo].[VH] ([VHId]),
    CONSTRAINT [FK_CardiologicalECG_VH1] FOREIGN KEY ([RVHId]) REFERENCES [dbo].[VH] ([VHId])
);

