CREATE TABLE [dbo].[CardiologicalSurgery] (
    [CardiologicalSurgeryId]    INT            IDENTITY (1, 1) NOT NULL,
    [ResidentId]                INT            NULL,
    [CardiologicalSurgeryDate]  DATE           NULL,
    [DiseaseStatusId]           INT            NULL,
    [CPB]                       BIT            NULL,
    [EuroSCORE]                 FLOAT (53)     NULL,
    [CABGX]                     INT            NULL,
    [BypassB1Id]                INT            NULL,
    [SegmentB1Id]               INT            NULL,
    [BypassB2Id]                INT            NULL,
    [SegmentB2Id]               INT            NULL,
    [BypassB3Id]                INT            NULL,
    [SegmentB3Id]               INT            NULL,
    [BypassC1Id]                INT            NULL,
    [SegmentC1Id]               INT            NULL,
    [SegmentD1Id]               INT            NULL,
    [BypassC2Id]                INT            NULL,
    [SegmentC2Id]               INT            NULL,
    [SegmentD2Id]               INT            NULL,
    [BypassC3Id]                INT            NULL,
    [SegmentC3Id]               INT            NULL,
    [SegmentD3Id]               INT            NULL,
    [LFL]                       FLOAT (53)     NULL,
    [HFL]                       FLOAT (53)     NULL,
    [NaCl]                      INT            NULL,
    [GEL]                       INT            NULL,
    [Mannitol]                  INT            NULL,
    [BicarbonateTypeId]         INT            NULL,
    [NaHCO3]                    INT            NULL,
    [Heparin1]                  FLOAT (53)     NULL,
    [CaCl2]                     FLOAT (53)     NULL,
    [RBCCPB]                    INT            NULL,
    [FFPCPB]                    INT            NULL,
    [LiquidId]                  INT            NULL,
    [Other1]                    INT            NULL,
    [PrimaryVolume]             AS             (((((((([NaCl]+[GEL])+[Mannitol])+[NaHCO3])+[Heparin1])+[CaCl2])+[RBCCPB])+[FFPCPB])+[Other1]),
    [Na]                        INT            NULL,
    [Gelofusin]                 INT            NULL,
    [Man]                       INT            NULL,
    [NaHCO]                     INT            NULL,
    [Heparin2]                  FLOAT (53)     NULL,
    [CaCl]                      FLOAT (53)     NULL,
    [R]                         INT            NULL,
    [F]                         INT            NULL,
    [Other2]                    INT            NULL,
    [TotalVolume]               AS             (((((((((((((((((isnull([NaCl],(0))+isnull([GEL],(0)))+isnull([Mannitol],(0)))+isnull([NaHCO3],(0)))+isnull([Heparin1],(0)))+isnull([CaCl2],(0)))+isnull([RBCCPB],(0)))+isnull([FFPCPB],(0)))+isnull([Other1],(0)))+isnull([Na],(0)))+isnull([Gelofusin],(0)))+isnull([Man],(0)))+isnull([NaHCO],(0)))+isnull([Heparin2],(0)))+isnull([CaCl],(0)))+isnull([R],(0)))+isnull([F],(0)))+isnull([Other2],(0))),
    [ResidualVolume]            FLOAT (53)     NULL,
    [InPatientVolume]           AS             ((((((((((((((((((isnull([NaCl],(0))+isnull([GEL],(0)))+isnull([Mannitol],(0)))+isnull([NaHCO3],(0)))+isnull([Heparin1],(0)))+isnull([CaCl2],(0)))+isnull([RBCCPB],(0)))+isnull([FFPCPB],(0)))+isnull([Other1],(0)))+isnull([Na],(0)))+isnull([Gelofusin],(0)))+isnull([Man],(0)))+isnull([NaHCO],(0)))+isnull([Heparin2],(0)))+isnull([CaCl],(0)))+isnull([R],(0)))+isnull([F],(0)))+isnull([Other2],(0)))-isnull([ResidualVolume],(0))),
    [SkinIncisionStartTime]     DATETIME       NULL,
    [SkinIncisionCloseTime]     DATETIME       NULL,
    [TotalOperationTime]        AS             (CONVERT([float],datediff(minute,[SkinIncisionStartTime],[SkinIncisionCloseTime]),(0))),
    [CrossClampTime]            INT            NULL,
    [BypassTime]                INT            NULL,
    [CardioplegiaTypeId]        INT            NULL,
    [AnesthesiaTime]            INT            NULL,
    [RBCId]                     INT            NULL,
    [FFPId]                     INT            NULL,
    [PLTId]                     INT            NULL,
    [InotropicSupportId]        INT            NULL,
    [BloodLossVolume]           INT            NULL,
    [SkinTemperature]           FLOAT (53)     NULL,
    [ExtubatedPOD]              INT            NULL,
    [InitialHoursVentilated]    INT            NULL,
    [ReIntubation]              BIT            NULL,
    [AdditionalHoursVentilated] INT            NULL,
    [TotalHoursVentilated]      AS             (isnull([InitialHoursVentilated],(0))+isnull([AdditionalHoursVentilated],(0))),
    [Hb]                        INT            NULL,
    [Hct]                       INT            NULL,
    [Platelet]                  INT            NULL,
    [Creatinine]                INT            NULL,
    [APTT]                      INT            NULL,
    [Sodium]                    INT            NULL,
    [Potassium]                 INT            NULL,
    [PH]                        FLOAT (53)     NULL,
    [PaO2]                      INT            NULL,
    [PaCO2]                     INT            NULL,
    [ICULength]                 INT            NULL,
    [DischargeDate]             DATE           NULL,
    [CSDLength]                 AS             (CONVERT([int],datediff(day,[CardiologicalSurgeryDate],[DischargeDate]),(0))),
    [Mortality]                 BIT            NULL,
    [DeathDate]                 DATE           NULL,
    [DeathCauseId]              INT            NULL,
    [Comment]                   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CardiologicalSurgery] PRIMARY KEY CLUSTERED ([CardiologicalSurgeryId] ASC),
    CONSTRAINT [FK_CardiologicalSurgery_BicarbonateType] FOREIGN KEY ([BicarbonateTypeId]) REFERENCES [dbo].[BicarbonateType] ([BicarbonateTypeId]),
    CONSTRAINT [FK_CardiologicalSurgery_BloodProduct] FOREIGN KEY ([RBCId]) REFERENCES [dbo].[BloodProduct] ([BloodProductId]),
    CONSTRAINT [FK_CardiologicalSurgery_BloodProduct1] FOREIGN KEY ([FFPId]) REFERENCES [dbo].[BloodProduct] ([BloodProductId]),
    CONSTRAINT [FK_CardiologicalSurgery_BloodProduct2] FOREIGN KEY ([PLTId]) REFERENCES [dbo].[BloodProduct] ([BloodProductId]),
    CONSTRAINT [FK_CardiologicalSurgery_Bypass] FOREIGN KEY ([BypassB1Id]) REFERENCES [dbo].[Bypass] ([BypassId]),
    CONSTRAINT [FK_CardiologicalSurgery_Bypass1] FOREIGN KEY ([BypassB2Id]) REFERENCES [dbo].[Bypass] ([BypassId]),
    CONSTRAINT [FK_CardiologicalSurgery_Bypass2] FOREIGN KEY ([BypassB3Id]) REFERENCES [dbo].[Bypass] ([BypassId]),
    CONSTRAINT [FK_CardiologicalSurgery_Bypass3] FOREIGN KEY ([BypassC1Id]) REFERENCES [dbo].[Bypass] ([BypassId]),
    CONSTRAINT [FK_CardiologicalSurgery_Bypass4] FOREIGN KEY ([BypassC2Id]) REFERENCES [dbo].[Bypass] ([BypassId]),
    CONSTRAINT [FK_CardiologicalSurgery_Bypass5] FOREIGN KEY ([BypassC3Id]) REFERENCES [dbo].[Bypass] ([BypassId]),
    CONSTRAINT [FK_CardiologicalSurgery_CardioplegiaType] FOREIGN KEY ([CardioplegiaTypeId]) REFERENCES [dbo].[CardioplegiaType] ([CardioplegiaTypeId]),
    CONSTRAINT [FK_CardiologicalSurgery_DeathCause] FOREIGN KEY ([DeathCauseId]) REFERENCES [dbo].[DeathCause] ([DeathCauseId]),
    CONSTRAINT [FK_CardiologicalSurgery_InotropicSupport] FOREIGN KEY ([InotropicSupportId]) REFERENCES [dbo].[InotropicSupport] ([InotropicSupportId]),
    CONSTRAINT [FK_CardiologicalSurgery_Liquid] FOREIGN KEY ([LiquidId]) REFERENCES [dbo].[Liquid] ([LiquidId]),
    CONSTRAINT [FK_CardiologicalSurgery_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE,
    CONSTRAINT [FK_CardiologicalSurgery_Segment] FOREIGN KEY ([SegmentB1Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment1] FOREIGN KEY ([SegmentB2Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment2] FOREIGN KEY ([SegmentB3Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment3] FOREIGN KEY ([SegmentC1Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment4] FOREIGN KEY ([SegmentD1Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment5] FOREIGN KEY ([SegmentC2Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment6] FOREIGN KEY ([SegmentD2Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment7] FOREIGN KEY ([SegmentC3Id]) REFERENCES [dbo].[Segment] ([SegmentId]),
    CONSTRAINT [FK_CardiologicalSurgery_Segment8] FOREIGN KEY ([SegmentD3Id]) REFERENCES [dbo].[Segment] ([SegmentId])
);

