CREATE TABLE [dbo].[CardiologicalObjective] (
    [CardiologicalObjectiveId]   INT           IDENTITY (1, 1) NOT NULL,
    [ResidentId]                 INT           NULL,
    [CardiologicalObjectiveDate] DATE          NULL,
    [Temperature]                FLOAT (53)    NULL,
    [Pulse]                      INT           NULL,
    [RNIBP]                      NVARCHAR (50) NULL,
    [LNIBP]                      NVARCHAR (50) NULL,
    [LungId]                     INT           NULL,
    [HeartSoundTypeId]           INT           NULL,
    [HeartMurmurTypeId]          INT           NULL,
    [RCBId]                      INT           NULL,
    [LCBId]                      INT           NULL,
    [AbdominalStatusId]          INT           NULL,
    [LiverId]                    INT           NULL,
    [RRAId]                      INT           NULL,
    [LRAId]                      INT           NULL,
    [RADPId]                     INT           NULL,
    [LADPId]                     INT           NULL,
    [PeripherialStatusId]        INT           NULL,
    [PhysicianId]                INT           NULL,
    CONSTRAINT [PK_CardiologicalObjective] PRIMARY KEY CLUSTERED ([CardiologicalObjectiveId] ASC),
    CONSTRAINT [FK_CardiologicalObjective_AbdominalStatus] FOREIGN KEY ([AbdominalStatusId]) REFERENCES [dbo].[AbdominalStatus] ([AbdominalStatusId]),
    CONSTRAINT [FK_CardiologicalObjective_ArteriaStatus] FOREIGN KEY ([RRAId]) REFERENCES [dbo].[ArteriaStatus] ([ArteriaStatusId]),
    CONSTRAINT [FK_CardiologicalObjective_ArteriaStatus1] FOREIGN KEY ([LRAId]) REFERENCES [dbo].[ArteriaStatus] ([ArteriaStatusId]),
    CONSTRAINT [FK_CardiologicalObjective_ArteriaStatus2] FOREIGN KEY ([RADPId]) REFERENCES [dbo].[ArteriaStatus] ([ArteriaStatusId]),
    CONSTRAINT [FK_CardiologicalObjective_ArteriaStatus3] FOREIGN KEY ([LADPId]) REFERENCES [dbo].[ArteriaStatus] ([ArteriaStatusId]),
    CONSTRAINT [FK_CardiologicalObjective_CaroticBruit] FOREIGN KEY ([RCBId]) REFERENCES [dbo].[CaroticBruit] ([CaroticBruitId]),
    CONSTRAINT [FK_CardiologicalObjective_CaroticBruit1] FOREIGN KEY ([LCBId]) REFERENCES [dbo].[CaroticBruit] ([CaroticBruitId]),
    CONSTRAINT [FK_CardiologicalObjective_HeartMurmurType] FOREIGN KEY ([HeartMurmurTypeId]) REFERENCES [dbo].[HeartMurmurType] ([HeartMurmurTypeId]),
    CONSTRAINT [FK_CardiologicalObjective_HeartSoundType] FOREIGN KEY ([HeartSoundTypeId]) REFERENCES [dbo].[HeartSoundType] ([HeartSoundTypeId]),
    CONSTRAINT [FK_CardiologicalObjective_Liver] FOREIGN KEY ([LiverId]) REFERENCES [dbo].[Liver] ([LiverId]),
    CONSTRAINT [FK_CardiologicalObjective_Lung] FOREIGN KEY ([LungId]) REFERENCES [dbo].[Lung] ([LungId]),
    CONSTRAINT [FK_CardiologicalObjective_PeripherialStatus] FOREIGN KEY ([PeripherialStatusId]) REFERENCES [dbo].[PeripherialStatus] ([PeripherialStatusId]),
    CONSTRAINT [FK_CardiologicalObjective_Physician] FOREIGN KEY ([PhysicianId]) REFERENCES [dbo].[Physician] ([PhysicianId]),
    CONSTRAINT [FK_CardiologicalObjective_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE
);

