CREATE TABLE [dbo].[CardiologicalExamination] (
    [CardiologicalExaminationId]   INT        IDENTITY (1, 1) NOT NULL,
    [ResidentId]                   INT        NULL,
    [CardiologicalExaminationDate] DATE       NULL,
    [BloodGroupId]                 INT        NULL,
    [RhFactorId]                   INT        NULL,
    [T3]                           FLOAT (53) NULL,
    [T4]                           FLOAT (53) NULL,
    [TTH]                          FLOAT (53) NULL,
    [CRP]                          FLOAT (53) NULL,
    [RF]                           INT        NULL,
    [ASLO]                         INT        NULL,
    [HIVStatusId]                  INT        NULL,
    [HBSStatusId]                  INT        NULL,
    [HCVStatusId]                  INT        NULL,
    [TPHAStatusId]                 INT        NULL,
    [BRUStatusId]                  INT        NULL,
    [Hb]                           FLOAT (53) NULL,
    [RBC]                          FLOAT (53) NULL,
    [FI]                           FLOAT (53) NULL,
    [MeanHbRBC]                    INT        NULL,
    [HCT]                          FLOAT (53) NULL,
    [Platelete]                    FLOAT (53) NULL,
    [Leukocyte]                    FLOAT (53) NULL,
    [Myelocyte]                    FLOAT (53) NULL,
    [Metamyelocyte]                FLOAT (53) NULL,
    [StabLeukocyte]                FLOAT (53) NULL,
    [SegmentedLeukocyte]           FLOAT (53) NULL,
    [Eosinophil]                   FLOAT (53) NULL,
    [Basophil]                     FLOAT (53) NULL,
    [Lymphocyte]                   FLOAT (53) NULL,
    [Monocyte]                     FLOAT (53) NULL,
    [ESR]                          INT        NULL,
    [ProteinTotal]                 FLOAT (53) NULL,
    [albumin]                      INT        NULL,
    [Urea]                         FLOAT (53) NULL,
    [Creatinine]                   FLOAT (53) NULL,
    [UricAcid]                     FLOAT (53) NULL,
    [Glucose]                      FLOAT (53) NULL,
    [BilirubinTotal]               FLOAT (53) NULL,
    [BilirubinDirect]              FLOAT (53) NULL,
    [ALT]                          FLOAT (53) NULL,
    [AST]                          FLOAT (53) NULL,
    [Potassium]                    FLOAT (53) NULL,
    [Sodium]                       FLOAT (53) NULL,
    [Calcium]                      FLOAT (53) NULL,
    [AAmilaza]                     INT        NULL,
    [CK]                           INT        NULL,
    [CKMB]                         INT        NULL,
    [TroponinStatusId]             INT        NULL,
    [Cholesterol]                  FLOAT (53) NULL,
    [Triglyceride]                 FLOAT (53) NULL,
    [HDL]                          FLOAT (53) NULL,
    [LDL]                          FLOAT (53) NULL,
    [PT]                           INT        NULL,
    [INR]                          FLOAT (53) NULL,
    [PI]                           FLOAT (53) NULL,
    [APTT]                         FLOAT (53) NULL,
    [Fibrinogen]                   INT        NULL,
    [UrineProtein]                 INT        NULL,
    [UrineLeucocyte]               INT        NULL,
    [UrineErithrocyte]             INT        NULL,
    [UrineDensity]                 INT        NULL,
    [UrineCylinderStatusId]        INT        NULL,
    [UrineMicroorganismStatusId]   INT        NULL,
    CONSTRAINT [PK_CardiologicalExamination] PRIMARY KEY CLUSTERED ([CardiologicalExaminationId] ASC),
    CONSTRAINT [FK_CardiologicalExamination_BloodGroup] FOREIGN KEY ([BloodGroupId]) REFERENCES [dbo].[BloodGroup] ([BloodGroupId]),
    CONSTRAINT [FK_CardiologicalExamination_BRUStatus] FOREIGN KEY ([BRUStatusId]) REFERENCES [dbo].[BRUStatus] ([BRUStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_HBSStatus] FOREIGN KEY ([HBSStatusId]) REFERENCES [dbo].[HBSStatus] ([HBSStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_HCVStatus] FOREIGN KEY ([HCVStatusId]) REFERENCES [dbo].[HCVStatus] ([HCVStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_HIVStatus] FOREIGN KEY ([HIVStatusId]) REFERENCES [dbo].[HIVStatus] ([HIVStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE,
    CONSTRAINT [FK_CardiologicalExamination_RhFactor] FOREIGN KEY ([RhFactorId]) REFERENCES [dbo].[RhFactor] ([RhFactorId]),
    CONSTRAINT [FK_CardiologicalExamination_TPHAStatus] FOREIGN KEY ([TPHAStatusId]) REFERENCES [dbo].[TPHAStatus] ([TPHAStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_TroponinStatus] FOREIGN KEY ([TroponinStatusId]) REFERENCES [dbo].[TroponinStatus] ([TroponinStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_UrineCylinderStatus] FOREIGN KEY ([UrineCylinderStatusId]) REFERENCES [dbo].[UrineCylinderStatus] ([UrineCylinderStatusId]),
    CONSTRAINT [FK_CardiologicalExamination_UrineMicroorganismStatus] FOREIGN KEY ([UrineMicroorganismStatusId]) REFERENCES [dbo].[UrineMicroorganismStatus] ([UrineMicroorganismStatusId])
);

