CREATE TABLE [dbo].[CardiologicalCatheterization] (
    [CardiologicalCatheterizationId]   INT            IDENTITY (1, 1) NOT NULL,
    [ResidentId]                       INT            NULL,
    [CardiologicalCatheterizationDate] DATE           NULL,
    [DominanceTypeId]                  INT            NULL,
    [LM]                               BIT            NULL,
    [LMStenosis]                       INT            NULL,
    [LAD1]                             BIT            NULL,
    [LAD1Stenosis]                     INT            NULL,
    [LAD2]                             BIT            NULL,
    [LAD2Stenosis]                     INT            NULL,
    [LAD3]                             BIT            NULL,
    [LAD3Stenosis]                     INT            NULL,
    [Diag1]                            BIT            NULL,
    [Diag1Stenosis]                    INT            NULL,
    [Diag2]                            BIT            NULL,
    [Diag2Stenosis]                    INT            NULL,
    [Cx1]                              BIT            NULL,
    [Cx1Stenosis]                      INT            NULL,
    [Cx2]                              BIT            NULL,
    [Cx2Stenosis]                      INT            NULL,
    [Cx3]                              BIT            NULL,
    [Cx3Stenosis]                      INT            NULL,
    [Rm]                               BIT            NULL,
    [RmStenosis]                       INT            NULL,
    [OM1]                              BIT            NULL,
    [OM1Stenosis]                      INT            NULL,
    [OM2]                              BIT            NULL,
    [OM2Stenosis]                      INT            NULL,
    [OM3]                              BIT            NULL,
    [OM3Stenosis]                      INT            NULL,
    [OM4]                              BIT            NULL,
    [OM4Stenosis]                      INT            NULL,
    [RCA1]                             BIT            NULL,
    [RCA1Stenosis]                     INT            NULL,
    [RCA2]                             BIT            NULL,
    [RCA2Stenosis]                     INT            NULL,
    [RCA3]                             BIT            NULL,
    [RCA3Stenosis]                     INT            NULL,
    [PDA]                              BIT            NULL,
    [PDAStenosis]                      INT            NULL,
    [PL1]                              BIT            NULL,
    [PL1Stenosis]                      INT            NULL,
    [PL2]                              BIT            NULL,
    [PL2Stenosis]                      INT            NULL,
    [LVGraphy]                         BIT            NULL,
    [LVEDP]                            INT            NULL,
    [LVEDV]                            INT            NULL,
    [LVESV]                            INT            NULL,
    [LVEF]                             INT            NULL,
    [PhysicianId]                      INT            NULL,
    [CatheterizationMovieURL]          NVARCHAR (MAX) NULL,
    [CatheterizationImageURL]          NVARCHAR (MAX) NULL,
    [Comment]                          NVARCHAR (255) NULL,
    CONSTRAINT [PK_CardiologicalCatheterization] PRIMARY KEY CLUSTERED ([CardiologicalCatheterizationId] ASC),
    CONSTRAINT [FK_CardiologicalCatheterization_DominanceType] FOREIGN KEY ([DominanceTypeId]) REFERENCES [dbo].[DominanceType] ([DominanceTypeId]),
    CONSTRAINT [FK_CardiologicalCatheterization_Physician] FOREIGN KEY ([PhysicianId]) REFERENCES [dbo].[Physician] ([PhysicianId]),
    CONSTRAINT [FK_CardiologicalCatheterization_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE
);

