CREATE TABLE [dbo].[CardiologicalCase] (
    [CardiologicalCaseId]            INT            IDENTITY (1, 1) NOT NULL,
    [ResidentId]                     INT            NULL,
    [OutPatient]                     BIT            NULL,
    [ConsultationDate]               DATE           NULL,
    [InHospital]                     BIT            NULL,
    [StartDate]                      DATE           NULL,
    [DischargeDate]                  DATE           NULL,
    [Duration]                       INT            NULL,
    [CAD]                            BIT            NULL,
    [CCSStatus]                      BIT            NULL,
    [CCSId]                          INT            NULL,
    [HBCriteriaStatus]               BIT            NULL,
    [HBCriteriaId]                   INT            NULL,
    [HITStatus]                      BIT            NULL,
    [HITId]                          INT            NULL,
    [NYHAStatus]                     BIT            NULL,
    [NYHAId]                         INT            NULL,
    [ShockTypeStatus]                BIT            NULL,
    [ShockTypeId]                    INT            NULL,
    [CATDStatus]                     BIT            NULL,
    [CATDId]                         INT            NULL,
    [CHDStatus]                      BIT            NULL,
    [CHDId]                          INT            NULL,
    [HVDStatus]                      BIT            NULL,
    [HVDId]                          INT            NULL,
    [CadiomyopathyStatus]            BIT            NULL,
    [CadiomyopathyId]                INT            NULL,
    [NormalHeart]                    BIT            NULL,
    [MainDiagnose]                   NVARCHAR (4000) NULL,
    [OtherDiseaseId]                 INT            NULL,
    [TreatmentTypeId]                INT            NULL,
    [ReferralOrganizationId]         INT            NULL,
    [DeathStatus]                    BIT            NULL,
    [DeathDate]                      DATE           NULL,
    [MortalityTypeId]                INT            NULL,
    [DeathCauseId]                   INT            NULL,
    [DeathOrganizationId]            INT            NULL,
    [Weight]                         INT            NULL,
    [Height]                         INT            NULL,
    [BSA]                            INT            NULL,
    [BMI]                            INT            NULL,
    [SmokingStatusId]                INT            NULL,
    [MovementStatusId]               INT            NULL,
    [AlcoholUsageId]                 INT            NULL,
    [ImmunologicalStatus]            BIT            NULL,
    [ImmunologicalStatusId]          INT            NULL,
    [CardiologicalInheritance]       BIT            NULL,
    [ClimaxStatusId]                 INT            NULL,
    [DiabetesMellitusStatus]         BIT            NULL,
    [Glucose]                        FLOAT (53)     NULL,
    [StrokeStatus]                   BIT            NULL,
    [StroceCount]                    INT            NULL,
    [StrokeTypeId]                   INT            NULL,
    [PulmonaryDiseaseStatus]         BIT            NULL,
    [PulmonaryDiseaseId]             INT            NULL,
    [COPDId]                         INT            NULL,
    [PVDTStatus]                     BIT            NULL,
    [PVDTId]                         INT            NULL,
    [RheumatismStatus]               BIT            NULL,
    [RheumatizmDurationId]           INT            NULL,
    [InfectiousEndocarditisStatus]   BIT            NULL,
    [InfectiousEndocarditisId]       INT            NULL,
    [BloodCholesterolId]             INT            NULL,
    [HypertensionStatus]             BIT            NULL,
    [HypertensionDurationId]         INT            NULL,
    [UrogenitalicDiseaseStatus]      BIT            NULL,
    [UrogenitalicDiseaseId]          INT            NULL,
    [GastrointestinalDiseaseStatus]  BIT            NULL,
    [GastrointestinalDiseaseId]      INT            NULL,
    [ImmunosuppressiveTherapyStatus] BIT            NULL,
    [ResuscitationStatus]            BIT            NULL,
    [DentalDiseaseId]                INT            NULL,
    [DiseaseStatusId]                INT            NULL,
    [SmokingTypeId]                  INT            NULL,
    CONSTRAINT [PK_CardiologicalCase] PRIMARY KEY CLUSTERED ([CardiologicalCaseId] ASC),
    CONSTRAINT [FK_CardiologicalCase_AlcoholUsage] FOREIGN KEY ([AlcoholUsageId]) REFERENCES [dbo].[AlcoholUsage] ([AlcoholUsageId]),
    CONSTRAINT [FK_CardiologicalCase_BloodCholesterol] FOREIGN KEY ([BloodCholesterolId]) REFERENCES [dbo].[BloodCholesterol] ([BloodCholesterolId]),
    CONSTRAINT [FK_CardiologicalCase_Cadiomyopathy] FOREIGN KEY ([CadiomyopathyId]) REFERENCES [dbo].[Cadiomyopathy] ([CadiomyopathyId]),
    CONSTRAINT [FK_CardiologicalCase_CATD] FOREIGN KEY ([CATDId]) REFERENCES [dbo].[CATD] ([CATDId]),
    CONSTRAINT [FK_CardiologicalCase_CCS] FOREIGN KEY ([CCSId]) REFERENCES [dbo].[CCS] ([CCSId]),
    CONSTRAINT [FK_CardiologicalCase_CHD] FOREIGN KEY ([CHDId]) REFERENCES [dbo].[CHD] ([CHDId]),
    CONSTRAINT [FK_CardiologicalCase_ClimaxStatus] FOREIGN KEY ([ClimaxStatusId]) REFERENCES [dbo].[ClimaxStatus] ([ClimaxStatusId]),
    CONSTRAINT [FK_CardiologicalCase_COPD] FOREIGN KEY ([COPDId]) REFERENCES [dbo].[COPD] ([COPDId]),
    CONSTRAINT [FK_CardiologicalCase_DeathCause] FOREIGN KEY ([DeathCauseId]) REFERENCES [dbo].[DeathCause] ([DeathCauseId]),
    CONSTRAINT [FK_CardiologicalCase_DeathOrganization] FOREIGN KEY ([DeathOrganizationId]) REFERENCES [dbo].[DeathOrganization] ([DeathOrganizationId]),
    CONSTRAINT [FK_CardiologicalCase_DentalDisease] FOREIGN KEY ([DentalDiseaseId]) REFERENCES [dbo].[DentalDisease] ([DentalDiseaseId]),
    CONSTRAINT [FK_CardiologicalCase_DiseaseStatus] FOREIGN KEY ([DiseaseStatusId]) REFERENCES [dbo].[DiseaseStatus] ([DiseaseStatusId]),
    CONSTRAINT [FK_CardiologicalCase_GastrointestinalDisease] FOREIGN KEY ([GastrointestinalDiseaseId]) REFERENCES [dbo].[GastrointestinalDisease] ([GastrointestinalDiseaseId]),
    CONSTRAINT [FK_CardiologicalCase_HBCriteria] FOREIGN KEY ([HBCriteriaId]) REFERENCES [dbo].[HBCriteria] ([HBCriteriaId]),
    CONSTRAINT [FK_CardiologicalCase_HIT] FOREIGN KEY ([HITId]) REFERENCES [dbo].[HIT] ([HITId]),
    CONSTRAINT [FK_CardiologicalCase_HVD] FOREIGN KEY ([HVDId]) REFERENCES [dbo].[HVD] ([HVDId]),
    CONSTRAINT [FK_CardiologicalCase_HypertensionDuration] FOREIGN KEY ([HypertensionDurationId]) REFERENCES [dbo].[HypertensionDuration] ([HypertensionDurationId]),
    CONSTRAINT [FK_CardiologicalCase_ImmunologicalStatus] FOREIGN KEY ([ImmunologicalStatusId]) REFERENCES [dbo].[ImmunologicalStatus] ([ImmunologicalStatusId]),
    CONSTRAINT [FK_CardiologicalCase_InfectiousEndocarditis] FOREIGN KEY ([InfectiousEndocarditisId]) REFERENCES [dbo].[InfectiousEndocarditis] ([InfectiousEndocarditisId]),
    CONSTRAINT [FK_CardiologicalCase_MortalityType] FOREIGN KEY ([MortalityTypeId]) REFERENCES [dbo].[MortalityType] ([MortalityTypeId]),
    CONSTRAINT [FK_CardiologicalCase_MovementStatus] FOREIGN KEY ([MovementStatusId]) REFERENCES [dbo].[MovementStatus] ([MovementStatusId]),
    CONSTRAINT [FK_CardiologicalCase_NYHA] FOREIGN KEY ([NYHAId]) REFERENCES [dbo].[NYHA] ([NYHAId]),
    CONSTRAINT [FK_CardiologicalCase_OtherDisease] FOREIGN KEY ([OtherDiseaseId]) REFERENCES [dbo].[OtherDisease] ([OtherDiseaseId]),
    CONSTRAINT [FK_CardiologicalCase_PulmonaryDisease] FOREIGN KEY ([PulmonaryDiseaseId]) REFERENCES [dbo].[PulmonaryDisease] ([PulmonaryDiseaseId]),
    CONSTRAINT [FK_CardiologicalCase_PVDT] FOREIGN KEY ([PVDTId]) REFERENCES [dbo].[PVDT] ([PVDTId]),
    CONSTRAINT [FK_CardiologicalCase_ReferralOrganization] FOREIGN KEY ([ReferralOrganizationId]) REFERENCES [dbo].[ReferralOrganization] ([ReferralOrganizationId]),
    CONSTRAINT [FK_CardiologicalCase_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE,
    CONSTRAINT [FK_CardiologicalCase_RheumatizmDuration] FOREIGN KEY ([RheumatizmDurationId]) REFERENCES [dbo].[RheumatizmDuration] ([RheumatizmDurationId]),
    CONSTRAINT [FK_CardiologicalCase_ShockType] FOREIGN KEY ([ShockTypeId]) REFERENCES [dbo].[ShockType] ([ShockTypeId]),
    CONSTRAINT [FK_CardiologicalCase_SmokingStatus] FOREIGN KEY ([SmokingStatusId]) REFERENCES [dbo].[SmokingStatus] ([SmokingStatusId]),
    CONSTRAINT [FK_CardiologicalCase_SmokingType] FOREIGN KEY ([SmokingTypeId]) REFERENCES [dbo].[SmokingType] ([SmokingTypeId]),
    CONSTRAINT [FK_CardiologicalCase_StrokeType] FOREIGN KEY ([StrokeTypeId]) REFERENCES [dbo].[StrokeType] ([StrokeTypeId]),
    CONSTRAINT [FK_CardiologicalCase_TreatmentType] FOREIGN KEY ([TreatmentTypeId]) REFERENCES [dbo].[TreatmentType] ([TreatmentTypeId]),
    CONSTRAINT [FK_CardiologicalCase_UrogenitalicDisease] FOREIGN KEY ([UrogenitalicDiseaseId]) REFERENCES [dbo].[UrogenitalicDisease] ([UrogenitalicDiseaseId])
);

