CREATE TABLE [dbo].[CardiologicalDuplexScan] (
    [CardiologicalDuplexScanId]   INT        IDENTITY (1, 1) NOT NULL,
    [ResidentId]                  INT        NULL,
    [CardiologicalDuplexScanDate] DATETIME   NULL,
    [RCAStenosisId]               INT        NULL,
    [RCAStenosisDM]               FLOAT (53) NULL,
    [RCAStenosisPC]               FLOAT (53) NULL,
    [LSAStenosisId]               INT        NULL,
    [LSAStenosisDM]               FLOAT (53) NULL,
    [LSAStenosisPC]               FLOAT (53) NULL,
    [RCCStenosisId]               INT        NULL,
    [RCCStenosisDM]               FLOAT (53) NULL,
    [RCCStenosisPC]               FLOAT (53) NULL,
    [LCCStenosisId]               INT        NULL,
    [LCCStenosisDM]               FLOAT (53) NULL,
    [LCCStenosisPC]               FLOAT (53) NULL,
    [RCIStenosisId]               INT        NULL,
    [RCIStenosisDM]               FLOAT (53) NULL,
    [RCIStenosisPC]               FLOAT (53) NULL,
    [LCIStenosisId]               INT        NULL,
    [LCIStenosisDM]               FLOAT (53) NULL,
    [LCIStenosisPC]               FLOAT (53) NULL,
    [RCEStenosisId]               INT        NULL,
    [RCEStenosisDM]               FLOAT (53) NULL,
    [RCEStenosisPC]               FLOAT (53) NULL,
    [LCEStenosisId]               INT        NULL,
    [LCEStenosisDM]               FLOAT (53) NULL,
    [LCEStenosisPC]               FLOAT (53) NULL,
    [RVAStenosisId]               INT        NULL,
    [RVAStenosisDM]               FLOAT (53) NULL,
    [RVAStenosisPC]               FLOAT (53) NULL,
    [LVAStenosisId]               INT        NULL,
    [LVAStenosisDM]               FLOAT (53) NULL,
    [LVAStenosisPC]               FLOAT (53) NULL,
    CONSTRAINT [PK_Table_DuplexUSScans] PRIMARY KEY CLUSTERED ([CardiologicalDuplexScanId] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis] FOREIGN KEY ([RCAStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis1] FOREIGN KEY ([LSAStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis2] FOREIGN KEY ([RCCStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis3] FOREIGN KEY ([LCCStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis4] FOREIGN KEY ([RCIStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis5] FOREIGN KEY ([LCIStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis6] FOREIGN KEY ([RCEStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis7] FOREIGN KEY ([LCEStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis8] FOREIGN KEY ([RVAStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_DuplexStenosis9] FOREIGN KEY ([LVAStenosisId]) REFERENCES [dbo].[DuplexStenosis] ([DuplexStenosisId]),
    CONSTRAINT [FK_CardiologicalDuplexScan_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE
);

