CREATE TABLE [dbo].[CardiologicalCPB] (
    [CardiologicalCPBId] INT        IDENTITY (1, 1) NOT NULL,
    [ResidentId]         INT        NOT NULL,
    [CPBDate]            DATETIME   NULL,
    [CPBTime]            DATETIME   NULL,
    [SampleTypeId]       INT        NULL,
    [MAP]                INT        NULL,
    [RectalTemperature]  FLOAT (53) NULL,
    [ACT]                INT        NULL,
    [FiO2]               INT        NULL,
    [pH]                 FLOAT (53) NULL,
    [pO2]                INT        NULL,
    [pCO2]               INT        NULL,
    [SO2]                INT        NULL,
    [Ht]                 INT        NULL,
    [Hb]                 FLOAT (53) NULL,
    [Na]                 INT        NULL,
    [K]                  FLOAT (53) NULL,
    [Cl]                 FLOAT (53) NULL,
    [Ca]                 FLOAT (53) NULL,
    [Mg]                 FLOAT (53) NULL,
    [BebTypeId]          INT        NULL,
    [BEB]                INT        NULL,
    [HCO3]               FLOAT (53) NULL,
    [BUN]                FLOAT (53) NULL,
    [Lactosa]            FLOAT (53) NULL,
    [Glucosa]            FLOAT (53) NULL,
    [IonGap]             FLOAT (53) NULL,
    CONSTRAINT [PK_Table_CardiologicalCPB] PRIMARY KEY CLUSTERED ([CardiologicalCPBId] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_CardiologicalCPB_BebType] FOREIGN KEY ([BebTypeId]) REFERENCES [dbo].[BebType] ([BebTypeId]),
    CONSTRAINT [FK_CardiologicalCPB_Resident] FOREIGN KEY ([ResidentId]) REFERENCES [dbo].[Resident] ([ResidentId]) ON DELETE CASCADE,
    CONSTRAINT [FK_CardiologicalCPB_SampleType] FOREIGN KEY ([SampleTypeId]) REFERENCES [dbo].[SampleType] ([SampleTypeId])
);

